In [1]:
import cv2
import numpy as np
import face_recognition

In [2]:
imgRaihan = face_recognition.load_image_file('ImagesBasic/Raihan Sikdar.jpg')

In [3]:
np.size(imgRaihan)

1183200

In [4]:
print(imgRaihan)

[[[222 222 224]
  [221 221 223]
  [221 221 223]
  ...
  [166 161 158]
  [166 161 158]
  [166 161 158]]

 [[222 222 224]
  [221 221 223]
  [221 221 223]
  ...
  [166 161 158]
  [166 161 158]
  [166 161 158]]

 [[222 222 224]
  [221 221 223]
  [221 221 223]
  ...
  [166 161 158]
  [166 161 158]
  [166 161 158]]

 ...

 [[181 178 185]
  [167 168 173]
  [133 138 142]
  ...
  [ 73  77  78]
  [ 72  76  77]
  [ 70  74  75]]

 [[167 164 171]
  [158 157 163]
  [129 134 138]
  ...
  [ 73  77  78]
  [ 72  76  77]
  [ 71  75  76]]

 [[135 130 137]
  [137 136 142]
  [120 125 129]
  ...
  [ 72  76  77]
  [ 72  76  77]
  [ 72  76  77]]]


In [6]:
imgRaihan= cv2.cvtColor(imgRaihan, cv2.COLOR_BGR2RGB)

In [8]:
type(img(imgRaihan)

numpy.ndarray

In [9]:
imgTest = face_recognition.load_image_file('ImagesBasic/Kazi Sarwar.jpg')
imgTest = cv2.cvtColor(imgTest, cv2.COLOR_BGR2RGB)

In [10]:
faceLoc = face_recognition.face_locations(imgRaihan)[0]

In [11]:
type(faceLoc)

tuple

In [12]:
len(faceLoc)

4

In [13]:
faceLoc

(266, 365, 489, 142)

In [14]:
encodeRaihan = face_recognition.face_encodings(imgRaihan)[0]

In [15]:
type(encodeRaihan)

numpy.ndarray

In [16]:
np.size(encodeRaihan)

128

In [18]:
encodeRaihan

array([-0.11152276,  0.01487775,  0.05837865, -0.08818498, -0.1157174 ,
       -0.04168291, -0.02177132, -0.07131764,  0.0783496 , -0.09079588,
        0.19187057, -0.05218456, -0.23001696, -0.08310684,  0.0942738 ,
        0.11147951, -0.07297697, -0.06654717, -0.07549662, -0.08912263,
       -0.02642377,  0.0138378 ,  0.06904305,  0.03635114, -0.14288174,
       -0.40147462, -0.07736941, -0.07788914, -0.01140768, -0.05687096,
        0.00584533,  0.1355065 , -0.11836389,  0.01105282,  0.00273836,
        0.13432072, -0.12014921, -0.11266108,  0.22193909, -0.02258046,
       -0.13957576, -0.11301309,  0.05821356,  0.20149903,  0.17826621,
        0.00651874,  0.08216521,  0.00701172,  0.07142571, -0.25086582,
        0.09998637,  0.0880075 ,  0.04105217,  0.01430514,  0.18183737,
       -0.12380473,  0.03602912,  0.05296203, -0.14131673, -0.01319744,
       -0.00088623, -0.03028458, -0.05925829, -0.08739624,  0.26623783,
        0.14376472, -0.10926998, -0.03379424,  0.09704405, -0.15

In [19]:
cv2.rectangle(imgRaihan, (faceLoc[3], faceLoc[0]), (faceLoc[1], faceLoc[2]), (255, 0, 255), 2)

array([[[224, 222, 222],
        [223, 221, 221],
        [223, 221, 221],
        ...,
        [158, 161, 166],
        [158, 161, 166],
        [158, 161, 166]],

       [[224, 222, 222],
        [223, 221, 221],
        [223, 221, 221],
        ...,
        [158, 161, 166],
        [158, 161, 166],
        [158, 161, 166]],

       [[224, 222, 222],
        [223, 221, 221],
        [223, 221, 221],
        ...,
        [158, 161, 166],
        [158, 161, 166],
        [158, 161, 166]],

       ...,

       [[185, 178, 181],
        [173, 168, 167],
        [142, 138, 133],
        ...,
        [ 78,  77,  73],
        [ 77,  76,  72],
        [ 75,  74,  70]],

       [[171, 164, 167],
        [163, 157, 158],
        [138, 134, 129],
        ...,
        [ 78,  77,  73],
        [ 77,  76,  72],
        [ 76,  75,  71]],

       [[137, 130, 135],
        [142, 136, 137],
        [129, 125, 120],
        ...,
        [ 77,  76,  72],
        [ 77,  76,  72],
        [ 77,  76,  72]]

In [22]:
faceLocTest = face_recognition.face_locations(imgTest)[0]
encodeTest = face_recognition.face_encodings(imgTest)[0]
cv2.rectangle(imgTest, (faceLocTest[3], faceLocTest[0]), (faceLocTest[1], faceLocTest[2]), (255, 0, 255), 2)

array([[[250, 250, 250],
        [250, 250, 250],
        [250, 250, 250],
        ...,
        [250, 250, 250],
        [250, 250, 250],
        [250, 250, 250]],

       [[250, 250, 250],
        [250, 250, 250],
        [250, 250, 250],
        ...,
        [250, 250, 250],
        [250, 250, 250],
        [250, 250, 250]],

       [[250, 250, 250],
        [250, 250, 250],
        [250, 250, 250],
        ...,
        [250, 250, 250],
        [250, 250, 250],
        [250, 250, 250]],

       ...,

       [[ 96, 104, 103],
        [ 96, 104, 103],
        [ 96, 104, 103],
        ...,
        [  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1]],

       [[ 95, 103, 102],
        [ 95, 103, 102],
        [ 95, 103, 102],
        ...,
        [  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1]],

       [[ 95, 103, 102],
        [ 95, 103, 102],
        [ 95, 103, 102],
        ...,
        [  1,   1,   1],
        [  1,   1,   1],
        [  1,   1,   1]]

In [23]:
results = face_recognition.compare_faces([encodeRaihan], encodeTest)

In [24]:
type(results)

list

In [25]:
print(len(results))
results

1


[False]

In [26]:
type(results[0])

numpy.bool_

In [27]:
faceDis = face_recognition.face_distance([encodeRaihan], encodeTest)

In [28]:
type(faceDis)

numpy.ndarray

In [29]:
faceDis

array([0.63218516])